version: '3.8'

services:
  frontend:
    image: findmytraject_frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    image: findmytraject_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/findmydb
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
