FROM node:20

 WORKDIR /app

 COPY package*.json ./
 RUN npm install
 RUN npm install cors
RUN npm install react-native-google-places-autocomplete
RUN npx expo install @react-native-async-storage/async-storage
RUN npx expo install expo-speech


 COPY . .

 # Installer ngrok pour expo tunnel
RUN npm install --global @expo/ngrok@^4.1.0

 EXPOSE 8081

 CMD ["npx", "expo", "start", "--tunnel"]
